FROM python:3.11.2-slim-bullseye AS builder

RUN apt-get update && \
    apt-get upgrade --yes

RUN useradd --create-home python
USER python
WORKDIR /home/python

ENV VIRTUALENV=/home/python/venv
RUN python3 -m venv $VIRTUALENV
ENV PATH="$VIRTUALENV/bin:$PATH"

COPY --chown=python pyproject.toml constraints.txt ./

RUN python -m pip install --upgrade pip setuptools && \
    python -m pip install --no-cache-dir -c constraints.txt ".[dev]"

COPY --chown=python src/ src/
COPY --chown=python test/ test/

RUN python -m pip install . -c constraints.txt
RUN python -m pytest test/unit/
RUN python -m flake8 src/
RUN python -m isort src/ --check
RUN python -m black src/ --check --quiet
RUN python -m pylint src/ --disable=C0114,C0116,R1705
RUN python -m bandit -r src/ --quiet
RUN python -m pip wheel --wheel-dir dist/ . -c constraints.txt


FROM python:3.11.2-slim-bullseye

RUN apt-get update && \
    apt-get upgrade --yes

RUN useradd --create-home python
USER python
WORKDIR /home/python

ENV VIRTUALENV=/home/python/venv
RUN python3 -m venv $VIRTUALENV
ENV PATH="$VIRTUALENV/bin:$PATH"

COPY --from=builder /home/python/dist/page_tracker*.whl /home/python

RUN python -m pip install --upgrade pip setuptools && \
    python -m pip install --no-cache-dir page_tracker*.whl

CMD ["flask", "--app", "page_tracker.app", "run", \
     "--host", "0.0.0.0", "--port", "5000"]
