name: Continous Intregation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    name: Build Docker image and run end-to-end tests
    runs-on: self-hosted
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3
      - name: Start the services
        run: >
          docker compose up -d
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v4.0.0
        if: ${{ github.event_name == 'push' }}
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/page-tracker:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/page-tracker:latest
